pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      set -euxo pipefail
      dotnet build
      dotnet test --no-build --logger 'trx' --logger 'console;verbosity=normal'
      dotnet pack --no-build --output=$(Build.ArtifactStagingDirectory)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/*.trx'
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: NuGet