variables:
- group: ApiKeys
- name: configuration
  value: Release

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      set -euxo pipefail
      dotnet build --configuration $(configuration)
      dotnet test --no-build --configuration $(configuration) --logger 'trx' --logger 'console;verbosity=normal'
      dotnet pack --no-build --configuration $(configuration) --output=$(Build.ArtifactStagingDirectory)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/*.trx'
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: NuGet
  - script: |
      dotnet nuget push --api-key $API_KEY --source "NuGetOrg" $(Build.ArtifactStagingDirectory)/*.nupkg
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
    env:
      API_KEY: $(NuGetOrgApiKey)