variables:
  configuration: Release

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      set -euxo pipefail
      dotnet build --configuration $(configuration)
      dotnet test --no-build --configuration $(configuration) --logger 'trx' --logger 'console;verbosity=normal'
      dotnet pack --no-build --configuration $(configuration) --output=$(Build.ArtifactStagingDirectory)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/*.trx'
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: NuGet
  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: NugetOrg
  - script: |
      dotnet nuget push --api-key AzureArtifacts --source "NuGetOrg"  $(Build.ArtifactStagingDirectory)/*.nupkg